services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true